//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LazyPortal.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>.cdg</string>
  <string>.idx</string>
  <string>.srt</string>
  <string>.sub</string>
  <string>.utf</string>
  <string>.ass</string>
  <string>.ssa</string>
  <string>.aqt</string>
  <string>.jss</string>
  <string>.psb</string>
  <string>.rt</string>
  <string>.sami</string>
  <string>.smi</string>
  <string>.txt</string>
  <string>.smil</string>
  <string>.stl</string>
  <string>.usf</string>
  <string>.dks</string>
  <string>.pjs</string>
  <string>.mpl2</string>
  <string>.mks</string>
  <string>.vtt</string>
  <string>.tt</string>
  <string>.ttml</string>
  <string>.dfxp</string>
  <string>.scc</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Subtitle_Extensions {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Subtitle_Extensions"]));
            }
            set {
                this["Subtitle_Extensions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>.mp4</string>
  <string>.264</string>
  <string>.avc</string>
  <string>.h264</string>
  <string>.x264</string>
  <string>.avi</string>
  <string>.flv</string>
  <string>.mp4</string>
  <string>.m4v</string>
  <string>.mpg</string>
  <string>.mpeg</string>
  <string>.m2v</string>
  <string>.mpv</string>
  <string>.evo</string>
  <string>.evob</string>
  <string>.vob</string>
  <string>.ts</string>
  <string>.m2ts</string>
  <string>.mts</string>
  <string>.m1v</string>
  <string>.m2v</string>
  <string>.mka</string>
  <string>.mks</string>
  <string>.mkv</string>
  <string>.mk3d</string>
  <string>.webm</string>
  <string>.webmv</string>
  <string>.webma</string>
  <string>.ogv</string>
  <string>.mov</string>
  <string>.rmvb</string>
  <string>.rv</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Video_Extensions {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Video_Extensions"]));
            }
            set {
                this["Video_Extensions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\MKV Convertions")]
        public string merge_destination {
            get {
                return ((string)(this["merge_destination"]));
            }
            set {
                this["merge_destination"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("219, 0, 36")]
        public global::System.Drawing.Color red {
            get {
                return ((global::System.Drawing.Color)(this["red"]));
            }
            set {
                this["red"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 219, 109")]
        public global::System.Drawing.Color green {
            get {
                return ((global::System.Drawing.Color)(this["green"]));
            }
            set {
                this["green"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 174, 219")]
        public global::System.Drawing.Color blue {
            get {
                return ((global::System.Drawing.Color)(this["blue"]));
            }
            set {
                this["blue"] = value;
            }
        }
    }
}
